print("                                                     __________________________")
print("                                                    /                          \\")
print("                                                   /    /       \\ \\             \\")
print("                                                   |                            |")
print("                                                   /                           /")
print("                                                   |         _____\\ \\| | /   /")
print("                                                   |        /                |")
print("                                                   |       |         ___     |")
print("                                                  /        |            \\    |")
print("                                                  |        |             \\   |   ")
print("                                                  |        |         ___     |")
print("                                                  |         \       (__o )   |")
print("                                                  |        ___               |")
print("                                                  |       |                  | ")
print("                                                   \      | |                 \  ")
print("                                                    |     | ____               \    ")
print("                                                    |     |               (* ___\    ")  
print("                                                    |     |           __     |") 
print("                                                    |     |        //________|")  
print("                                                    |    /          |_|_|_|_|_____/\  ")
print("                                                      \\  |        \\  __            |")
print("                                                         |          -----__________/")
print("                                                         |          /")
print("                                                         |         /")
